fix(openapi-coverage-stream): null pointer during parameter coverage calculator
fixing `NullPointerException` source in `openapi-coverage-stream`.
analysis based on following extracted stacktrace:

```shell
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local5>" is null
	at [...]ParameterCoverageCalculator.isParameterPresent(ParameterCoverageCalculator.java:162)
	[...]
```